server:
  port: 8081
spring:
  application:
    name: union
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: 123456
    url: jdbc:mysql://localhost:3306/bridge?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0 #操作的是0号数据库
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
bujurui:
  path: C:\23429\bujurui\img\

